language: python
python:
  - '3.6'

install:
  - pip install -U setuptools>=40.1
  - pip install .

script: ./scanpy-scripts-tests.bats

cache:
  pip: false
  directories:
    - post_install_tests

before_cache:
  - rm -rf post_install_tests/outputs

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: ffzJLnBtBLXHbrZch65cGUzZGut0CVqeIhNqZ+mOr4czZSURGZVhUaiXkGp4ovefmH4wvdQGfKyUBn6oTKZHuJVUJt0Fzek1u+gvEpBmgQ8SLqXyy8gqXVoUgdKz9u6zSLrHwSTgmMAjnFeKFej4XTuuj/PFcyLXzEtD46l1DVqMxxbFrLAmdk9cYhKKoHB7QgS0uemlofQLimIr8uvaImlTmDg0OXzwM+oAKZXtm7lfZD+CPC3IKmfKS2jD8L0Gm7PJb5syBvgL0joUadHffMMnUV6zBTnqhGR7qSsWZZu7SMrFkgW8QAKNbEjk0jRwqqVG6mUarN/LUVjREG5qEmmwP6jWSMhSfx3m1EOsLmlADL1kljf6EWmetUyCyX3c9CGO/udNd2Kh5CkwwDRF1c2Csw0Jzs2aeptKc1urQUR7pjEBbneyj5/2UCFu9Kom3VKE0lXjVPoGSKnAHoBq0lqs/C4fiYpUzbMBl6gvkIk7YCgkQbKO61abGr/Eb/ae6HyGwsRRQ9ZQfvI/DQto8KfB5UZulZ0wgpe+oMgFpEJ8R/QynrxOtG1R/jxqoG55fCgvIsLRIylq54S1hDou5clOP6GPzRvMz20Qoiez2vobTcU5AmJ0pnfrqx238ZJExb3nPOdbCqQCK/pwml0EUyBTXNhgzCNWWlN0TMD1kFo=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
