language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -U setuptools>=40.1
  - pip install .

script: ./scanpy-scripts-tests.sh

cache:
  pip: true
  directories:
    - post_install_tests

before_cache:
  - rm -rf post_install_tests/outputs
